;;; riece-mcat.el --- message catalog for Japanese -*- coding: iso-2022-jp -*-
;; Copyright (C) 2007 Daiki Ueno

;; Author: Daiki Ueno <ueno@unixuser.org>

;; This file is part of Riece.

;; This program is free software; you can redistribute it and/or modify
;; it under the terms of the GNU General Public License as published by
;; the Free Software Foundation; either version 2, or (at your option)
;; any later version.

;; This program is distributed in the hope that it will be useful,
;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.	 See the
;; GNU General Public License for more details.

;; You should have received a copy of the GNU General Public License
;; along with GNU Emacs; see the file COPYING.  If not, write to the
;; Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
;; Boston, MA 02110-1301, USA.

;;; Commentary:

;; To update riece-mcat-japanese-alist, do `make update-mcat'.

;;; Code:

(defconst riece-mcat-japanese-alist
  '(("\nSymbols in the leftmost column:\n\n   +     The add-on is enabled.\n   -     The add-on is disabled.\n   ?     The add-on is not insinuated.\n         The add-on is not loaded.\n" . "\n左端のシンボル:\n\n   +     有効なアドオン\n   -     無効なアドオン\n   ?     組み込まれていないアドオン\n         ロードされていないアドオン\n")
    ("\nUseful keys:\n\n   `\\[riece-command-enable-addon]' to enable the current add-on.\n   `\\[riece-command-disable-addon]' to disable the current add-on.\n   `\\[riece-command-insinuate-addon]' to insinuate the current add-on.\n   `\\[riece-command-uninstall-addon]' to uninstall the current add-on.\n   `\\[riece-command-unload-addon]' to unload the current add-on.\n   `\\[riece-command-save-variables]' to save the current setting.\n" . "\n便利なキー:\n\n   `\\[riece-command-enable-addon]' アドオンを有効化\n   `\\[riece-command-disable-addon]' アドオンを無効化\n   `\\[riece-command-insinuate-addon]' アドオンを組み込み\n   `\\[riece-command-uninstall-addon]' アドオンの除外\n   `\\[riece-command-unload-addon]' アドオンをアンロード\n   `\\[riece-command-save-variables]' 設定を保存\n")
    ("%2d: %s %s (%d bytes)\n" . "%2d: %s %s (%d バイト)\n")
    ("%S: switch to %s; down-mouse-3: more options" . "%S: %s に移動; down-mouse-3: その他のオプション")
    ("%d users on %s: " . "%d 人が %s にいます: ")
    ("%d users: " . "%d 人: ")
    ("%s (%s) has joined %s" . "%s (%s) が %s に参加しました")
    ("%s (%s) has joined %s\n" . "%s (%s) が %s に参加しました\n")
    ("%s has left %s" . "%s が %s を離れました")
    ("%s has left IRC" . "%s が IRC を離れました")
    ("%s invites %s to %s" . "%s が %s を %s に招待しています")
    ("%s is %s (%s)" . "%s は %s (%s)")
    ("%s is %s idle" . "%s は %s アイドル状態")
    ("%s is (%s)" . "%s は (%s)")
    ("%s is away: %s" . "%s は離席中: %s")
    ("%s is running on %s: %s" . "%s が %s で動いています: %s")
    ("%s kicked %s out from %s" . "%s が %s を %s から蹴り出しました")
    ("%s kicked %s out from %s\n" . "%s が %s を %s から蹴り出しました\n")
    ("%s killed %s" . "%s が %s を KILL しました")
    ("%s users, topic: %s\n" . "%s 人、トピック: %s\n")
    ("%s will be insinuated.  Continue? " . "%s は組み込まれていません。続行しますか? ")
    ("%s: %s users, topic: %s" . "%s: %s 人、トピック: %s\n")
    ("(no description)" . "(説明なし)")
    ("Action: " . "アクション: ")
    ("Add-on %S disabled" . "アドオン %S が無効になりました")
    ("Add-on %S enabled" . "アドオン %S が有効になりました")
    ("Add-on %S is already disabled" . "アドオン %S は既に無効です")
    ("Add-on %S is already enabled" . "アドオン %S は既に有効です")
    ("Add-on %S is already insinuated" . "アドオン %S は既に組み込まれています")
    ("Add-on %S is insinuated" . "アドオン %S が組み込まれました")
    ("Add-on %S is not allowed to unload" . "アドオン %S はアンロードできません")
    ("Add-on %S is not insinuated" . "アドオン %S は組み込まれていません")
    ("Add-on %S is uninstalled" . "アドオン %S が除外されました")
    ("Add-on %S is unloaded" . "アドオン %S がアンロードされました")
    ("Add-on: " . "アドオン: ")
    ("Allow channel members to play the hangman game." . "チャンネルの参加者がハングマンで遊べるようになります")
    ("Already registered" . "登録済みです")
    ("Away message: " . "離席のメッセージ: ")
    ("Ban pattern: " . "立入禁止パターン: ")
    ("Be notified if messages arrives." . "メッセージが届くと通知されます")
    ("Beginning of buffer" . "バッファの先頭です")
    ("CTCP (Client To Client Protocol) support." . "CTCP (Client To Client Protocol) 対応")
    ("CTCP CLIENTINFO for %s (%s) = %s" . "%s (%s) の CTCP CLIENTINFO = %s")
    ("CTCP CLIENTINFO from %s (%s) to %s" . "%s (%s) が %s に CTCP CLIENTINFO")
    ("CTCP PING for %s (%s) = %d sec" . "%s (%s) の CTCP PING = %d 秒")
    ("CTCP PING from %s (%s) to %s" . "%s (%s) が %s に CTCP PING")
    ("CTCP TIME for %s (%s) = %s" . "%s (%s) の CTCP TIME = %s")
    ("CTCP TIME from %s\n" . "%s から CTCP TIME\n")
    ("CTCP TIME from %s (%s) to %s" . "%s (%s) が %s に CTCP TIME")
    ("CTCP VERSION for %s (%s) = %s" . "%s (%s) の CTCP VERSION = %s")
    ("CTCP VERSION from %s (%s) to %s" . "%s (%s) が %s に CTCP VERSION")
    ("Can't find completion for \"%s\"" . "\"%s\" に対する補完が見つかりません")
    ("Change Nickname" . "ニックネームを変更")
    ("Change Window Layout..." . "ウィンドウレイアウトを変更...")
    ("Change layout: " . "変更後のレイアウト: ")
    ("Change mode for channel/user: " . "モードを変更するチャンネルまたはユーザ: ")
    ("Channel/User: " . "チャンネルまたはユーザ: ")
    ("Channels" . "チャンネル一覧")
    ("Close Server" . "サーバとの接続を閉じる")
    ("Close server: " . "接続を閉じるサーバ: ")
    ("Collect URL in IRC buffers." . "バッファに出てきた URL を集めます")
    ("Command to execute on \"%s\":" . "\"%s\" で実行するコマンド: ")
    ("Connect to IRC server via async proxy." . "接続切れを防ぐために外部のプロセス (aproxy.rb) を介して IRC サーバに接続します")
    ("Connecting to %s..." . "%s に接続しています...")
    ("Connecting to %s...done" . "%s に接続しています...完了")
    ("Connecting to %s...failed: %S" . "%s に接続しています...失敗: %S")
    ("Connecting to IRC server..." . "IRC サーバに接続しています...")
    ("Connecting to IRC server...done" . "IRC サーバに接続しています...完了")
    ("Connecting to IRC server...failed: %S" . "IRC サーバに接続しています...失敗: %S")
    ("Convert Japanese to roman string by KAKASI." . "KAKASI を用いて日本語をローマ字に変換します")
    ("Created on %s\n" . "%s に作成されました\n")
    ("DCC file sending protocol support (written in Ruby.)" . "DCC ファイル転送 (Ruby による実装)")
    ("Define aliases for IRC names." . "ニックネームやチャンネル名の別名定義")
    ("Detect keywords in IRC buffers." . "バッファに出てきたキーワードの検出")
    ("Display Channel Buffer" . "チャンネルバッファの表示")
    ("Display Channel List Buffer" . "チャンネル一覧バッファの表示")
    ("Display User List Buffer" . "ユーザ一覧バッファの表示")
    ("Display X-Face & Colour Face images in IRC buffers (BBDB)." . "X-Face や色付きの Face 画像を表示 (BBDB 利用)")
    ("Display X-Face in IRC buffers." . "X-Face や色付き Face 画像を表示 (LSDB 利用)")
    ("Display icons in IRC buffers." . "アイコンを表示")
    ("Display notification to desktop." . "デスクトップに通知")
    ("Display toolbar icons." . "ツールバーのアイコンを表示")
    ("Display useful buttons in IRC buffers." . "ボタンを表示")
    ("Encrypt/decrypt messages." . "メッセージの暗号化・復号")
    ("End of buffer" . "バッファの終端です")
    ("Enter the element of kill-ring." . "kill-ring から一行発言")
    ("Erroneous nickname \"%s\".  Choose a new one: " . "不正なニックネーム \"%s\"。新しいニックネーム: ")
    ("Evaluate an input string as an elisp form." . "入力行を Elisp の式として評価")
    ("Evaluate input string as a Ruby program." . "入力行を Ruby の式として評価")
    ("File: " . "ファイル: ")
    ("Finger user: " . "身元を調べるユーザ: ")
    ("Free old IRC messages to save memory usage." . "古いメッセージを消去してメモリ消費を減らす")
    ("Freeze Channel Buffer" . "自動スクロールを禁止")
    ("Freeze Channel Buffer Until Next Message" . "メッセージが来るまで自動スクロールを禁止")
    ("Guess the next channel, using multiple methods." . "複数の方法で移動先のチャンネルを予測")
    ("Help register nicknames in LSDB rolodex program." . "LSDB 住所録にニックネームを登録")
    ("Highlight IRC buffers." . "バッファの色付け")
    ("Ignore messages from some users." . "指定したユーザからのメッセージを無視")
    ("Invite User" . "ユーザを招待する")
    ("Invite user: " . "招待するユーザ: ")
    ("Inviting %s\n" . "%s を招待しています\n")
    ("Inviting %s to %s" . "%s を %s に招待しています")
    ("Join Channel" . "チャンネルに参加する")
    ("Join channel/user (default %s): " . "参加するチャンネルまたはユーザ (既定値 %s): ")
    ("Join channel/user: " . "参加するチャンネルまたはユーザ: ")
    ("Keep an IRC connection." . "接続を維持")
    ("Key for %s: " . "%s のキー: ")
    ("Key for %s: Quit" . "%s のキー: 中止")
    ("Kick User" . "ユーザを蹴り出す")
    ("Kick user: " . "蹴り出すユーザ: ")
    ("LIST pattern: " . "LIST のパターン: ")
    ("List Channel" . "チャンネルを調べる")
    ("Logging in to %s..." . "%s にログインしています...")
    ("Logging in to %s...done" . "%s にログインしています...完了")
    ("Logging in to IRC server..." . "IRC サーバにログインしています...")
    ("Logging in to IRC server...done" . "IRC サーバにログインしています...完了")
    ("Manage Add-ons" . "アドオンの管理")
    ("Manage history of channel shifting." . "チャンネル移動の履歴")
    ("Mark As Away" . "離席状態にする")
    ("Mark channels where new messages arrived." . "新しいメッセージが届いたチャンネルをマーク")
    ("Mark up control sequences in IRC buffers." . "コントロールシーケンスによる色付け")
    ("Message to user: " . "ユーザへのメッセージ: ")
    ("Message: " . "メッセージ")
    ("Mode (? for help)" . "モード (ヘルプは ?)")
    ("Mode by %s: %s\n" . "%s によるモード設定: %s\n")
    ("Mode for %s: %s" . "%s のモード: %s")
    ("Mode on %s by %s: %s" . "%s のモードが %s により設定されました: %s")
    ("Mode: " . "モード: ")
    ("NAMES pattern: " . "NAMES のパターン: ")
    ("Next Channel" . "次のチャンネル")
    ("Nickname \"%s\" already in use.  Choose a new one: " . "ニックネーム \"%s\" は既に使用されています。新しいニックネーム: ")
    ("No changes made.  Save anyway? " . "変更がありませんが、保存しますか? ")
    ("No channel" . "チャンネルなし")
    ("No information given" . "情報がありません")
    ("No server process" . "サーバのプロセスがありません")
    ("No text to send" . "送信するテキストがありません")
    ("None" . "なし")
    ("Online: " . "オンライン: ")
    ("Open Server" . "サーバに接続")
    ("Open URL..." . "URL を開く...")
    ("Open URL: " . "開く URL: ")
    ("Open server: " . "接続するサーバ: ")
    ("Part Channel" . "チャンネルから離脱する")
    ("Part from channel/user (default %s): " . "離脱するチャンネルまたはユーザ (既定値 %s): ")
    ("Password for %s: " . "%s のパスワード: ")
    ("Password for %s: Quit" . "%s のパスワード: 中止")
    ("Password incorrect from %s." . "%s のパスワードが不正です。")
    ("Password: " . "パスワード: ")
    ("Password: Quit" . "パスワード: 中止")
    ("Pretend to be a psychotherapist." . "心理療法士になりすます")
    ("Prevent miss-operation in the command buffer." . "コマンドバッファでの誤操作を防ぐ")
    ("Previous Channel" . "前のチャンネル")
    ("Quit IRC" . "IRC をやめる")
    ("Really quit IRC? " . "本当に IRC をやめますか? ")
    ("Really want to query LIST without argument? " . "本当に引数なしの LIST を発行しますか? ")
    ("Really want to query NAMES without argument? " . "本当に引数なしの NAMES を発行しますか? ")
    ("Really want to query WHO without argument? " . "本当に引数なしの WHO を発行しますか? ")
    ("Receiving %s from %s...(%s/%s)" . "%s を %s から受信中...(%s/%s)")
    ("Receiving %s from %s...done" . "%s を %s から受信中...完了")
    ("Recent messages of the day:\n" . "最近のメッセージ (今日中):\n")
    ("Recent messages up to %d lines:\n" . "最近のメッセージ (%d 行まで):\n")
    ("Redraw Layout" . "画面の再描画")
    ("Remove SKK's preedit mark before sending messages." . "SKK の変換前文字列を送らないようにする")
    ("Save IRC logs." . "ログを保存")
    ("Save as (default %s) " . "保存先 (既定値 %s) ")
    ("Saving %s..." . "%s を保存しています...")
    ("Saving %s...done" . "%s を保存しています...完了")
    ("Search keywords by Google." . "キーワードを Google で検索")
    ("Send your status to Twitter." . "Twitter にステータス情報を送る")
    ("Sending %s...(%s/%d)" . "%s を送信中...(%s/%d)")
    ("Sending %s...done" . "%s を送信中...完了")
    ("Sending QUIT to \"%s\"..." . "\"%s\" に QUIT を送信しています...")
    ("Sending QUIT to \"%s\"...done" . "\"%s\" に QUIT を送信しています...完了")
    ("Sending QUIT..." . "QUIT を送信しています...")
    ("Sending QUIT...done" . "QUIT を送信しています...完了")
    ("Server: " . "サーバ: ")
    ("Servers" . "サーバ一覧")
    ("Set +o for users" . "+o するユーザ")
    ("Set +v for users" . "+v するユーザ")
    ("Set Channel Topic" . "チャンネルのトピック")
    ("Set topic: " . "新しいトピック: ")
    ("Setup Riece's command menus." . "メニューバーの利用")
    ("Submit Bug Report" . "バグを報告")
    ("Switch To Channel" . "チャンネルに移動")
    ("Switch to channel/user: " . "移動先のチャンネルまたはユーザ: ")
    ("Switch to number: " . "移動先の番号: ")
    ("Toggle..." . "トグル...")
    ("Topic by %s: %s\n" . "%s によるトピック設定: %s\n")
    ("Topic for %s: %s" . "%s のトピック: ")
    ("Topic on %s by %s: %s" . "%s のトピックが %s により設定されました: %s")
    ("Topic: " . "トピック: ")
    ("Translate messages." . "メッセージの翻訳")
    ("Type \\[describe-mode] for help" . "ヘルプを見るには \\[describe-mode]")
    ("Type \\[riece-command-dcc-receive] to receive" . "受信するには \\[riece-command-dcc-receive]")
    ("Type \\[riece-command-join] to join the channel" . "チャンネルに参加するには \\[riece-command-join]")
    ("Unset +o for users" . "-o するユーザ")
    ("Unset +v for users" . "-v するユーザ")
    ("Use Riece only on the minibuffer." . "ミニバッファだけで Riece を使う")
    ("User: " . "ユーザ: ")
    ("Version" . "バージョン")
    ("WHO pattern: " . "WHO のパターン: ")
    ("[Available modes: " . "[使用可能なモード: ")
    ("days" . "日")
    ("hours" . "時間")
    ("minutes" . "分")
    ("on via server %s: %s" . "サーバ %s 経由: %s")
    ("seconds" . "秒")))

(provide 'riece-mcat-japanese)

;;; riece-mcat-japanese.el ends here
